name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: deps
      run: sudo apt install ninja-build cmake bison flex libinput-dev
    - name: mkdir
      run: mkdir generated.x86
    - name: configure
      run: cd generated.x86 && ../configure
    - name: ninja
      run: cd generated.x86 && ninja
